package com.liany.csiserverapp.dao.database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liany.csiserverapp.diagnose.Alarm;
import com.liany.csiserverapp.diagnose.CellResultItemEntity;
import com.liany.csiserverapp.diagnose.CompareEntity;
import com.liany.csiserverapp.diagnose.ComparePhoto;
import com.liany.csiserverapp.diagnose.ContactsEntity;
import com.liany.csiserverapp.diagnose.CrimeItem;
import com.liany.csiserverapp.diagnose.EvidenceEntity;
import com.liany.csiserverapp.diagnose.GoodEntity;
import com.liany.csiserverapp.diagnose.ItemEntity;
import com.liany.csiserverapp.diagnose.KCTBASESTATIONDATABean;
import com.liany.csiserverapp.diagnose.Photo;
import com.liany.csiserverapp.diagnose.SceneWifiInfo;
import com.liany.csiserverapp.diagnose.ToolEntity;
import com.liany.csiserverapp.diagnose.WitnessEntity;
import com.liany.csiserverapp.diagnose.sysDict;
import com.liany.csiserverapp.diagnose.sysOrgan;
import com.liany.csiserverapp.diagnose.sysTechnician;
import com.liany.csiserverapp.diagnose.sysUser;

import com.liany.csiserverapp.dao.database.greenDao.db.AlarmDao;
import com.liany.csiserverapp.dao.database.greenDao.db.CellResultItemEntityDao;
import com.liany.csiserverapp.dao.database.greenDao.db.CompareEntityDao;
import com.liany.csiserverapp.dao.database.greenDao.db.ComparePhotoDao;
import com.liany.csiserverapp.dao.database.greenDao.db.ContactsEntityDao;
import com.liany.csiserverapp.dao.database.greenDao.db.CrimeItemDao;
import com.liany.csiserverapp.dao.database.greenDao.db.EvidenceEntityDao;
import com.liany.csiserverapp.dao.database.greenDao.db.GoodEntityDao;
import com.liany.csiserverapp.dao.database.greenDao.db.ItemEntityDao;
import com.liany.csiserverapp.dao.database.greenDao.db.KCTBASESTATIONDATABeanDao;
import com.liany.csiserverapp.dao.database.greenDao.db.PhotoDao;
import com.liany.csiserverapp.dao.database.greenDao.db.SceneWifiInfoDao;
import com.liany.csiserverapp.dao.database.greenDao.db.ToolEntityDao;
import com.liany.csiserverapp.dao.database.greenDao.db.WitnessEntityDao;
import com.liany.csiserverapp.dao.database.greenDao.db.sysDictDao;
import com.liany.csiserverapp.dao.database.greenDao.db.sysOrganDao;
import com.liany.csiserverapp.dao.database.greenDao.db.sysTechnicianDao;
import com.liany.csiserverapp.dao.database.greenDao.db.sysUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig alarmDaoConfig;
    private final DaoConfig cellResultItemEntityDaoConfig;
    private final DaoConfig compareEntityDaoConfig;
    private final DaoConfig comparePhotoDaoConfig;
    private final DaoConfig contactsEntityDaoConfig;
    private final DaoConfig crimeItemDaoConfig;
    private final DaoConfig evidenceEntityDaoConfig;
    private final DaoConfig goodEntityDaoConfig;
    private final DaoConfig itemEntityDaoConfig;
    private final DaoConfig kCTBASESTATIONDATABeanDaoConfig;
    private final DaoConfig photoDaoConfig;
    private final DaoConfig sceneWifiInfoDaoConfig;
    private final DaoConfig toolEntityDaoConfig;
    private final DaoConfig witnessEntityDaoConfig;
    private final DaoConfig sysDictDaoConfig;
    private final DaoConfig sysOrganDaoConfig;
    private final DaoConfig sysTechnicianDaoConfig;
    private final DaoConfig sysUserDaoConfig;

    private final AlarmDao alarmDao;
    private final CellResultItemEntityDao cellResultItemEntityDao;
    private final CompareEntityDao compareEntityDao;
    private final ComparePhotoDao comparePhotoDao;
    private final ContactsEntityDao contactsEntityDao;
    private final CrimeItemDao crimeItemDao;
    private final EvidenceEntityDao evidenceEntityDao;
    private final GoodEntityDao goodEntityDao;
    private final ItemEntityDao itemEntityDao;
    private final KCTBASESTATIONDATABeanDao kCTBASESTATIONDATABeanDao;
    private final PhotoDao photoDao;
    private final SceneWifiInfoDao sceneWifiInfoDao;
    private final ToolEntityDao toolEntityDao;
    private final WitnessEntityDao witnessEntityDao;
    private final sysDictDao sysDictDao;
    private final sysOrganDao sysOrganDao;
    private final sysTechnicianDao sysTechnicianDao;
    private final sysUserDao sysUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        alarmDaoConfig = daoConfigMap.get(AlarmDao.class).clone();
        alarmDaoConfig.initIdentityScope(type);

        cellResultItemEntityDaoConfig = daoConfigMap.get(CellResultItemEntityDao.class).clone();
        cellResultItemEntityDaoConfig.initIdentityScope(type);

        compareEntityDaoConfig = daoConfigMap.get(CompareEntityDao.class).clone();
        compareEntityDaoConfig.initIdentityScope(type);

        comparePhotoDaoConfig = daoConfigMap.get(ComparePhotoDao.class).clone();
        comparePhotoDaoConfig.initIdentityScope(type);

        contactsEntityDaoConfig = daoConfigMap.get(ContactsEntityDao.class).clone();
        contactsEntityDaoConfig.initIdentityScope(type);

        crimeItemDaoConfig = daoConfigMap.get(CrimeItemDao.class).clone();
        crimeItemDaoConfig.initIdentityScope(type);

        evidenceEntityDaoConfig = daoConfigMap.get(EvidenceEntityDao.class).clone();
        evidenceEntityDaoConfig.initIdentityScope(type);

        goodEntityDaoConfig = daoConfigMap.get(GoodEntityDao.class).clone();
        goodEntityDaoConfig.initIdentityScope(type);

        itemEntityDaoConfig = daoConfigMap.get(ItemEntityDao.class).clone();
        itemEntityDaoConfig.initIdentityScope(type);

        kCTBASESTATIONDATABeanDaoConfig = daoConfigMap.get(KCTBASESTATIONDATABeanDao.class).clone();
        kCTBASESTATIONDATABeanDaoConfig.initIdentityScope(type);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        sceneWifiInfoDaoConfig = daoConfigMap.get(SceneWifiInfoDao.class).clone();
        sceneWifiInfoDaoConfig.initIdentityScope(type);

        toolEntityDaoConfig = daoConfigMap.get(ToolEntityDao.class).clone();
        toolEntityDaoConfig.initIdentityScope(type);

        witnessEntityDaoConfig = daoConfigMap.get(WitnessEntityDao.class).clone();
        witnessEntityDaoConfig.initIdentityScope(type);

        sysDictDaoConfig = daoConfigMap.get(sysDictDao.class).clone();
        sysDictDaoConfig.initIdentityScope(type);

        sysOrganDaoConfig = daoConfigMap.get(sysOrganDao.class).clone();
        sysOrganDaoConfig.initIdentityScope(type);

        sysTechnicianDaoConfig = daoConfigMap.get(sysTechnicianDao.class).clone();
        sysTechnicianDaoConfig.initIdentityScope(type);

        sysUserDaoConfig = daoConfigMap.get(sysUserDao.class).clone();
        sysUserDaoConfig.initIdentityScope(type);

        alarmDao = new AlarmDao(alarmDaoConfig, this);
        cellResultItemEntityDao = new CellResultItemEntityDao(cellResultItemEntityDaoConfig, this);
        compareEntityDao = new CompareEntityDao(compareEntityDaoConfig, this);
        comparePhotoDao = new ComparePhotoDao(comparePhotoDaoConfig, this);
        contactsEntityDao = new ContactsEntityDao(contactsEntityDaoConfig, this);
        crimeItemDao = new CrimeItemDao(crimeItemDaoConfig, this);
        evidenceEntityDao = new EvidenceEntityDao(evidenceEntityDaoConfig, this);
        goodEntityDao = new GoodEntityDao(goodEntityDaoConfig, this);
        itemEntityDao = new ItemEntityDao(itemEntityDaoConfig, this);
        kCTBASESTATIONDATABeanDao = new KCTBASESTATIONDATABeanDao(kCTBASESTATIONDATABeanDaoConfig, this);
        photoDao = new PhotoDao(photoDaoConfig, this);
        sceneWifiInfoDao = new SceneWifiInfoDao(sceneWifiInfoDaoConfig, this);
        toolEntityDao = new ToolEntityDao(toolEntityDaoConfig, this);
        witnessEntityDao = new WitnessEntityDao(witnessEntityDaoConfig, this);
        sysDictDao = new sysDictDao(sysDictDaoConfig, this);
        sysOrganDao = new sysOrganDao(sysOrganDaoConfig, this);
        sysTechnicianDao = new sysTechnicianDao(sysTechnicianDaoConfig, this);
        sysUserDao = new sysUserDao(sysUserDaoConfig, this);

        registerDao(Alarm.class, alarmDao);
        registerDao(CellResultItemEntity.class, cellResultItemEntityDao);
        registerDao(CompareEntity.class, compareEntityDao);
        registerDao(ComparePhoto.class, comparePhotoDao);
        registerDao(ContactsEntity.class, contactsEntityDao);
        registerDao(CrimeItem.class, crimeItemDao);
        registerDao(EvidenceEntity.class, evidenceEntityDao);
        registerDao(GoodEntity.class, goodEntityDao);
        registerDao(ItemEntity.class, itemEntityDao);
        registerDao(KCTBASESTATIONDATABean.class, kCTBASESTATIONDATABeanDao);
        registerDao(Photo.class, photoDao);
        registerDao(SceneWifiInfo.class, sceneWifiInfoDao);
        registerDao(ToolEntity.class, toolEntityDao);
        registerDao(WitnessEntity.class, witnessEntityDao);
        registerDao(sysDict.class, sysDictDao);
        registerDao(sysOrgan.class, sysOrganDao);
        registerDao(sysTechnician.class, sysTechnicianDao);
        registerDao(sysUser.class, sysUserDao);
    }
    
    public void clear() {
        alarmDaoConfig.clearIdentityScope();
        cellResultItemEntityDaoConfig.clearIdentityScope();
        compareEntityDaoConfig.clearIdentityScope();
        comparePhotoDaoConfig.clearIdentityScope();
        contactsEntityDaoConfig.clearIdentityScope();
        crimeItemDaoConfig.clearIdentityScope();
        evidenceEntityDaoConfig.clearIdentityScope();
        goodEntityDaoConfig.clearIdentityScope();
        itemEntityDaoConfig.clearIdentityScope();
        kCTBASESTATIONDATABeanDaoConfig.clearIdentityScope();
        photoDaoConfig.clearIdentityScope();
        sceneWifiInfoDaoConfig.clearIdentityScope();
        toolEntityDaoConfig.clearIdentityScope();
        witnessEntityDaoConfig.clearIdentityScope();
        sysDictDaoConfig.clearIdentityScope();
        sysOrganDaoConfig.clearIdentityScope();
        sysTechnicianDaoConfig.clearIdentityScope();
        sysUserDaoConfig.clearIdentityScope();
    }

    public AlarmDao getAlarmDao() {
        return alarmDao;
    }

    public CellResultItemEntityDao getCellResultItemEntityDao() {
        return cellResultItemEntityDao;
    }

    public CompareEntityDao getCompareEntityDao() {
        return compareEntityDao;
    }

    public ComparePhotoDao getComparePhotoDao() {
        return comparePhotoDao;
    }

    public ContactsEntityDao getContactsEntityDao() {
        return contactsEntityDao;
    }

    public CrimeItemDao getCrimeItemDao() {
        return crimeItemDao;
    }

    public EvidenceEntityDao getEvidenceEntityDao() {
        return evidenceEntityDao;
    }

    public GoodEntityDao getGoodEntityDao() {
        return goodEntityDao;
    }

    public ItemEntityDao getItemEntityDao() {
        return itemEntityDao;
    }

    public KCTBASESTATIONDATABeanDao getKCTBASESTATIONDATABeanDao() {
        return kCTBASESTATIONDATABeanDao;
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

    public SceneWifiInfoDao getSceneWifiInfoDao() {
        return sceneWifiInfoDao;
    }

    public ToolEntityDao getToolEntityDao() {
        return toolEntityDao;
    }

    public WitnessEntityDao getWitnessEntityDao() {
        return witnessEntityDao;
    }

    public sysDictDao getSysDictDao() {
        return sysDictDao;
    }

    public sysOrganDao getSysOrganDao() {
        return sysOrganDao;
    }

    public sysTechnicianDao getSysTechnicianDao() {
        return sysTechnicianDao;
    }

    public sysUserDao getSysUserDao() {
        return sysUserDao;
    }

}
